name: BootStrap Web

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      run: |
        apt-get update
        apt-get install -y ruby-full build-essential
    - name: Install Jekyll
      run: gem install jekyll bundler
    - name: Build Jekyll site
      run: bundle exec jekyll build
    - name: Install AWS CLI
      run: apt-get install -y awscli
    - name: Configure AWS credentials
      run: |
	      aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
        aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY_ID}
    - name: Sync with S3
      run: aws s3 sync _site/ s3://$S3_BUCKET_NAME/ --include "*.*" --delete


